import React,{useEffect,useRef,useState} from 'react'
import {useLocation,useNavigate,useParams} from 'react-router-dom'
import Navbar from '../components/Navbar.jsx'; import WebcamFeed from '../components/WebcamFeed.jsx'; import {sessionApi,signalsApi} from '../api/api.js'; import {useAuth} from '../context/AuthContext.jsx'
const EXAM_SECONDS=15*60
export default function AptitudeSession(){
 const {sessionId}=useParams(); const location=useLocation(); const navigate=useNavigate(); const {token}=useAuth();
 const subject=location.state?.subject||'General', difficulty=location.state?.difficulty||'MEDIUM', round=location.state?.round||1
 const questions=location.state?.questions||[]; const [current,setCurrent]=useState(0); const [answers,setAnswers]=useState({}); const [seconds,setSeconds]=useState(EXAM_SECONDS); const [stream,setStream]=useState(null); const [events,setEvents]=useState([]); const finished=useRef(false); const answersRef=useRef({})
 useEffect(()=>{answersRef.current=answers},[answers]); const q=questions[current]
 const addEvent=(type,message)=>setEvents(e=>[{type,message,time:new Date().toLocaleTimeString()},...e].slice(0,10))
 useEffect(()=>{const id=setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(id);finish('time expired');return 0}return s-1}),1000);return()=>clearInterval(id)},[])
 useEffect(()=>{if(!stream||!sessionId)return;let stop=false;const v=document.createElement('video'),c=document.createElement('canvas');v.srcObject=stream;v.muted=true;v.playsInline=true;v.play().catch(()=>{});const run=async()=>{if(stop||v.readyState<2)return;const w=v.videoWidth||640,h=v.videoHeight||480;c.width=Math.min(w,640);c.height=Math.round(c.width*h/w);const ctx=c.getContext('2d');ctx.drawImage(v,0,0,c.width,c.height);try{const r=await signalsApi.analyzeFrame(Number(sessionId),c.toDataURL('image/jpeg',.7));if(Number(r.faceCount)>1)addEvent('person','More than one face was detected.')}catch{}};const id=setInterval(run,3000);const first=setTimeout(run,1000);return()=>{stop=true;clearInterval(id);clearTimeout(first);v.pause();v.srcObject=null}},[stream,sessionId])
 async function finish(reason='submitted'){if(finished.current)return;finished.current=true;const final=answersRef.current;for(const item of questions){if(final[item.id]!==undefined){try{await sessionApi.submitAnswer(token,sessionId,{questionId:item.id,answerText:String(final[item.id])})}catch{}}}try{await sessionApi.complete(token,sessionId)}catch{}navigate(`/results/${sessionId}`,{state:{subject,difficulty,round,aptitude:true,integrityEvents:events}})}
 if(!q)return <div className="page-shell"><Navbar/><main className="dashboard-shell"><div className="card" style={{padding:24}}>Questions are still being generated. Please start the session again.</div></main></div>
 const code=q.type==='code'; const selected=answers[q.id]; const mm=Math.floor(seconds/60).toString().padStart(2,'0'),ss=(seconds%60).toString().padStart(2,'0')
 return <div className="page-shell aptitude-page"><Navbar/><main className="aptitude-shell"><header className="aptitude-command-bar professional-card"><div><span className="eyebrow">AI-GENERATED APTITUDE • ROUND {round}</span><h1>{subject} Assessment</h1></div><div className={seconds<120?'exam-timer danger':'exam-timer'}>⏱ {mm}:{ss}</div><div className="exam-progress"><span>Question {current+1} / {questions.length}</span><div><i style={{width:`${((current+1)/questions.length)*100}%`}}/></div></div></header>
 <div className="aptitude-layout"><section className="exam-card professional-card"><div className="exam-topline"><span>QUESTION {current+1}</span><small>{difficulty} • {code?'CODING':'MCQ'}</small></div><h2 className="aptitude-question">{q.text}</h2>
 {code?<div className="coding-answer-wrap"><div className="coding-editor-label">{q.language||'code'} · AI coding challenge</div><textarea className="code-answer-box" spellCheck={false} rows={16} value={selected??q.starterCode??''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}/></div>:<div className="mcq-options">{(q.options||[]).map((o,i)=><button key={i} className={selected===i?'mcq-option selected':'mcq-option'} onClick={()=>setAnswers(a=>({...a,[q.id]:i}))}><b>{String.fromCharCode(65+i)}</b><span>{o}</span><i>{selected===i?'✓':''}</i></button>)}</div>}
 <div className="exam-actions"><button className="btn-secondary" onClick={()=>setCurrent(i=>Math.max(0,i-1))} disabled={current===0}>← Previous</button>{current+1<questions.length?<button className="btn-primary" onClick={()=>setCurrent(i=>i+1)}>Save & Next →</button>:<button className="btn-primary" onClick={()=>finish()}>Submit Assessment</button>}</div></section>
 <aside className="exam-sidebar"><div className="question-palette professional-card"><span className="eyebrow">QUESTION PALETTE</span><div className="palette-grid">{questions.map((x,i)=><button key={x.id} onClick={()=>setCurrent(i)} className={`${current===i?'current ':''}${answers[x.id]!==undefined?'answered':''}`}>{i+1}</button>)}</div></div><div className="integrity-card professional-card"><span className="eyebrow">LIVE PROCTORING</span><h3>Camera & microphone</h3><p>Camera monitoring stays active while you answer.</p><div className="integrity-status"><span>Camera</span><b>{stream?'LIVE':'CHECKING'}</b></div><div className="integrity-status"><span>Round</span><b>{round} / 3</b></div></div><div style={{marginTop:12}}><WebcamFeed showLiveBadge={true} onStream={setStream}/></div></aside></div></main></div>
}
